logging:
  level: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quickid
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    validation-query: select 1;
    maxWait: 10000
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none

source:
  datasource:
    url: jdbc:mysql://localhost:3306/securitoo_identification
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    validation-query: select 1;
    maxWait: 10000
    
chunk:
  size: 100
